added more functionality

diff --git a/aufii b/aufii
--- a/aufii
+++ b/aufii
@@ -1,131 +1,170 @@
-#!/bin/bash
-### Automatically generate UEFI-boot entries
-usage() { printf "Usage:\t aufii \naufii is a simple interactive tool to automatically generate UEFI boot entries. It generates efibootmgr commands and exports them to a small executable. You can safely run the script as it does write nothing without further confirmation. \n [-h]\t<display help>\n "; 1>&2; exit 1; }
+#!/usr/bin/env bash
+#
+# aufii is a fast way to create UEFI-entries.
+# This script is hosted at https://github.com/mfgbhatti/auto-uefi. For new features,
+# improvements and bugs fill an issue in GitHub or make a pull request.
+# Pull Request are welcome!
 
+SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
+CONFIG_FILE="${SCRIPT_DIR}/auto-gen-uefi"
 
-# Compose [and execute] efibootmgr commands 
-while getopts :h OPT; do
-	case ${OPT} in
-		h)
-		usage;;
-	esac
-done
-shift $((OPTIND-1))
-read -r -p "Simple interactive tool to create UEFI-boot entries. No changes will be written to disk before confirmation. Start now (y/n)? " CHOICE
-case ${CHOICE} in
-y)	
-echo ...
-echo ...
-read -r -p "Please specify EFI partition: " str
-
-# Detect partitions
-#EFI=$(blkid | grep EFI | awk -F ':' '{print $1}')
-
-EFI=${str}
-EFIU=$(blkid | grep "${EFI}" | awk -F '"' '{print $2}')
-DISK=$(echo "${EFI}" | awk -F 'p' '{print $1}')
-PART=$(echo "${EFI}" | awk -F 'p' '{print $2}')
-AROT=$(lsblk| grep -w "/"|awk -F ' ' '{print $1}'|tail -c4)
-ROOT=$(blkid | grep "${AROT}"| awk -F '"' '{print $2}')
-SWAP=$(blkid | grep swap | awk -F '"' '{print $2}')
-P_S=$(blkid | grep "${SWAP}" | awk -F ':' '{print $1}')
-P_E=$(blkid | grep "${EFI}" | awk -F ':' '{print $1}')
-P_R=$(blkid | grep "${ROOT}"| awk -F ':' '{print $1}')
-
-echo ...
-echo ...
-read -r -p "Include microcode (amd/intel/no)? (a/i/n) " CHOICE
-case ${CHOICE} in
-a)
-echo "Including amd-ucode"
-UCODE="initrd=\amd-ucode.img"
-echo ...
-echo ...;;
-i)
-echo "Including intel-ucode"
-UCODE="initrd=\intel-ucode.img"
-echo ...
-echo ...;;
-n)
-echo "Not using microcode"
-echo ...
-echo ...;;
-esac;;
-n)
-echo "Aborted by user"
-exit 1;;
-esac
-shift $((OPTIND-1))
-
-# Choose kernel
-read -r -p "Choose your kernel: linux, linux-hardened, linux-lts, linux-zen (l/h/s/z) " CHOICE
-case ${CHOICE} in
-l) 
-echo "kernel is linux"
-echo ...
-echo ...
-KERN="";;
-h) 
-echo "kernel is linux-hardened"
-echo ...
-echo ...
-KERN="-hardened";;
-p) 
-echo "kernel is linux-lts"
-echo ...
-echo ...
-KERN="-lts";;
-z) 
-echo "kernel is linux-zen"
-echo ...
-echo ...
-KERN="-zen";;
-esac
-shift $((OPTIND-1))
-
-# Name
-read -r -p "Please label the boot entry (e.g. Arch-Linux): " str
-NAME=${str}
-shift $((OPTIND-1))
-
-# Compose commands
-FLBK=$(echo "efibootmgr --disk ${DISK} --part ${PART} --create --label \"${NAME}-Fallback\" --loader /vmlinuz-linux${KERN} --unicode 'root=UUID=${ROOT} resume=UUID=${SWAP} rw ${UCODE} initrd=\initramfs-linux${KERN}-fallback.img'")
-LINX=$(echo "efibootmgr --disk ${DISK} --part ${PART} --create --label \"${NAME}\" --loader /vmlinuz-linux${KERN} --unicode 'root=UUID=${ROOT} resume=UUID=${SWAP} rw ${UCODE} initrd=\initramfs-linux${KERN}.img'")
-
-# Prompt detected partitions and composed commands
-printf "Partitions detected:\nEFI:\t${P_E}\t${EFIU}\nRoot:\t${P_R}\t${ROOT}\nSwap:\t${P_S}\t${SWAP}\n"
-echo ...
-echo ...
-echo "Composed commands:"
-echo ...
-echo "${FLBK}"
-echo ...
-echo "${LINX}"
-echo ...
-echo "To add additional kernel parameters just choose the first option in the next step and edit the file before executing it."
-echo ...
-echo ...
-# Write to disk and execute or abort
-write_exec (){
-echo "#!/bin/bash" > UEFI_gen${KERN}
-echo "${FLBK}" >> UEFI_gen${KERN}
-echo "${LINX}" >> UEFI_gen${KERN}
-echo "exit 0" >> UEFI_gen${KERN}
-echo "# See man efibootmgr" >> UEFI_gen${KERN}
-chmod +x UEFI_gen${KERN}
-printf "Commands written to file UEFI_gen${KERN}"
+# Misc
+center() {
+	width="$(tput cols)"
+	padding="$(printf '%0.1s' \ {1..500})"
+	printf '%*.*s %s %*.*s\n' 0 "$(((width - 2 - ${#1}) / 2))" "$padding" "$1" 0 "$(((width - 1 - ${#1}) / 2))" "$padding"
 }
 
-read -r -p "Create executable, create and execute (sets UEFI boot entries) or abort (c/ce/a)? " CHOICE 
-case ${CHOICE} in
-c)  # write to file
-write_exec;;
-ce) # write to file and execute it
-write_exec
-./UEFI_gen${KERN} 
-printf "Changes written, poweroff and restart, don't reboot.";;
-a)  # abort
-printf "Aborted, no changes written to disk.\n";;
+title() {
+	echo " "
+	INPUT="${1//\"/}"
+	center "$INPUT"
+	echo " "
+}
+
+root_check() {
+    if [[ "$(id -u)" != "0" ]]; then
+        echo -ne "ERROR! This script must be run under the 'root' user!\n"
+        exit 0
+    fi
+}
+
+PROMPT="Please select a valid option: "
+
+# Logo
+logo() {
+	clear
+	center "                       .o88o.  o8o   o8o "
+	center "                       888 ''  '''   ''' "
+	center " .oooo.   oooo  oooo  o888oo  oooo  oooo "
+	center "'P  )88b  '888  '888   888    '888  '888 "
+	center " .oP'888   888   888   888     888   888 "
+	center "d8(  888   888   888   888     888   888 "
+	center "'Y888''8o  'V88V'V8P' o888o   o888o o888o"
+	title "Simple interactive tool to create UEFI-boot entries."
+}
+
+# Compose [and execute] efibootmgr commands
+logo
+
+echo -ne "No changes will be written to disk before confirmation.\n"
+read -r -p "Start now (y/n)? " CHOICE
+case $CHOICE in
+y | Y | yes | Yes | YES)
+	echo ""
+	echo -ne "Please specify EFI partition: \n"
+	PS3=$PROMPT
+	mapfile -t DISKLIST <<<"$(lsblk | grep 'part' | awk '{print "/dev/" substr($1,3)}')"
+	select DISK in "${DISKLIST[@]}"; do
+		EFI=$DISK
+		break
+	done
+	DISK=$(echo "$EFI" | awk -F 'p' '{print $1}')
+	PART=$(echo "$EFI" | awk -F 'p' '{print $2}')
+	#AROT=$(lsblk | grep -w "/" | awk -F ' ' '{print $1}' | tail -c4)
+	AROT=$(df -hT | grep /$ | awk '{print $1}')
+	ROOT=$(blkid -s UUID | grep "$AROT" | awk -F '"' '{print $2}')
+	echo ""
+	read -r -p "Is your system using swap partition (y/n)? " SWAP
+	case $SWAP in
+	y | Y | yes | Yes | YES)
+		SWAP=$(blkid -s UUID| grep swap | awk -F '"' '{print $2}')
+		SWAP_UUID=" resume=UUID=$SWAP"
+		;;
+	n | N | no | NO | No)
+		SWAP_UUID=""
+		;;
+	esac
+	;;
+n | N | no | NO | No)
+	echo "Aborted by user"
+	exit 1
+	;;
 esac
-shift $((OPTIND-1))
+
+# Choose kernel and microcode
+cd /boot || exit 0
+for f in ./*; do
+	case $f in
+	*intel*) UCODE="initrd=\intel-ucode.img" ;;
+	*amd*) UCODE="initrd=\amd-ucode.img" ;;
+	*lts*) KERN="-lts";;
+	*hard*) KERN="-hardened";;
+	*zen*) KERN="-zen";;
+	*) 
+		KERN=""
+		UCODE=""
+		;;
+	esac
+done
+cd "$SCRIPT_DIR" || exit 0
+
+
+# Name
+echo ""
+read -r -p "Please label the boot entry (default is Arch-Linux): " STR
+if [[ -z "$STR" ]]; then
+	STR="Arch-Linux"
+fi
+NAME=$STR
+
+# Compose commands
+FLBK="efibootmgr --disk $DISK --part $PART --create --label \"$NAME-Fallback\" --loader /vmlinuz-linux$KERN --unicode 'root=UUID=$ROOT$SWAP_UUID rw $UCODE initrd=\initramfs-linux$KERN-fallback.img'"
+LINX="efibootmgr --disk $DISK --part $PART --create --label \"$NAME\" --loader /vmlinuz-linux$KERN --unicode 'root=UUID=$ROOT$SWAP_UUID rw $UCODE initrd=\initramfs-linux$KERN.img'"
+
+# Create bash file to execute commands
+write_exec() {
+	cat <<EOF > "$CONFIG_FILE"
+#!/usr/bin/env bash
+#
+# aufii is a fast way to create UEFI-entries.
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program. If not, see <http://www.gnu.org/licenses/>.
+#
+# This script is hosted at https://github.com/mfgbhatti/auto-uefi. For new features,
+# improvements and bugs fill an issue in GitHub or make a pull request.
+# Pull Request are welcome!
+## For further information visit https://linux.die.net/man/8/efibootmgr. or
+## https://wiki.archlinux.org/title/EFISTUB for detailed information.
+## See man efibootmgr
+#
+# Generated by aufii
+#
+$FLBK
+$LINX
+exit 0
+EOF
+	chmod +x auto-gen
+	printf %s "Commands written to file $CONFIG_FILE"
+}
+
+# Write to disk and execute or abort
+echo ""
+echo -ne "Create executable bash file to edit or execute later,\n"
+echo -ne "create and execute user need to be root (sets UEFI boot entries)\n"
+read -r -p "or abort this script (c/ce/a)? " CHOICE
+case "$CHOICE" in
+c) # write to file
+	write_exec ;;
+ce) # write to file and execute it
+	root_check
+	write_exec
+	./"$CONFIG_FILE"
+	printf %s "Changes written, poweroff and restart, don't reboot."
+	;;
+a) # abort
+	printf %s "Aborted, no changes written to disk.\n"
+	;;
+esac
 exit 0
